<?php
include('init.php');

if(empty($_POST) === false) // ["group_name"]) || empty($_POST["email_list"]))
{ // form submitted without any data

	$e_list = explode(",", $_POST['email_list']); // obtain list of email IDs
	$name = $_POST['group_name']; // obtain group name

	$email_list = array();

	foreach($e_list as $email)
	{
		$email_list[] = sanitize(trim($email)); // clean - sanitize email IDs entered
	}

	$final_list_email = array(); // user who has an account with the system
	$pending_list_email = array(); // user that does not have an account with the system, but the emailId has been included in the list of intended group members

	foreach($email_list as $email)
	{
		if(!user_exists($email))
		{
			$pending_list_email[] = $email;
		}
		else
		{
			$final_list_email[] = $email;
		}
	}

	$x = check_group_name($final_list_email); // the function returns the group names of all group that every user in the intended list of users in the new group is already a part of
	if(in_array($name, $x)) // if a user is already a part of a group with the same name, throw an error
	{
		echo "<script>alert('Group Name is Invalid, Someone You Added Is Already Part Of A Group With The Same Name, Try Another Group Name'); window.location.href='user_home.php';</script>";
	}
	
	else
	{
		$groupId = create_group($name); // create the group in the databse and return an autogenerated groupID
		
		adduser_togroup($groupId, $final_list_email, 1); // add to usergroup table if user exists

		add_todues($final_list_email); // add user to dues table

		if(empty($pending_list_email)) // if everyone in the list of users has an account
		{
			echo "<script>alert('Group Successfully Created');window.location.href='user_home.php';</script>";
		}
		else // if a few emailIDs are not part of the system, store them in the pending user table in the database
		{
			adduser_togroup($groupId, $pending_list_email, 0); // add to pending list if user does not exist
			$pending = implode(", ", $pending_list_email);
			echo '<script> alert("Group Successfully Created without - ' . $pending . ' as they do not have an account with us");window.location.href="user_home.php";</script>';
		}
	}

	$_POST = array();
}

else
{
	echo '<script> alert("Please Enter All Details");window.location.href="user_home.php";</script>';
}
?>